# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='article',
            new_name='item',
        ),
    ]
