# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
