# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_item_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Count',
            new_name='Dictionary',
        ),
    ]
